# Generated by Django 5.2.17 on 2026-08-16 10:37

import django.db.models.deletion
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("code", "Source code"),
                            ("image", "Screenshot"),
                            ("xml", "XML file"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional context: what this is, what to ask Claude, etc.",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("javascript", "JavaScript"),
                            ("python", "Python"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("sql", "SQL"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("xml", "XML"),
                            ("json", "JSON"),
                            ("shell", "Shell"),
                            ("powershell", "PowerShell"),
                            ("text", "Plain text"),
                            ("other", "Other"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Pasted source code or XML content."
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        blank=True, null=True, upload_to=vault.models.upload_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
