# Generated by Django 5.2.17 on 2026-08-16 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="API name other scripts use to call this one (e.g. the Script Include class name). Auto-detected from the code when left blank; used for dependency detection.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="related_to",
            field=models.ForeignKey(
                blank=True,
                help_text="For screenshots: the script this screenshot belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="vault.item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="script_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("script_include", "Script Include"),
                    ("business_rule", "Business Rule"),
                    ("client_script", "Client Script"),
                    ("ui_page", "UI Page"),
                    ("ui_action", "UI Action"),
                    ("ui_macro", "UI Macro"),
                    ("scheduled_job", "Scheduled Job"),
                    ("fix_script", "Fix Script"),
                    ("rest_api", "Scripted REST API"),
                    ("widget", "Widget"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="vault.project",
            ),
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now=True)),
                (
                    "from_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_out",
                        to="vault.item",
                    ),
                ),
                (
                    "to_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_in",
                        to="vault.item",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dependencies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_item", "to_item"), name="unique_dependency_edge"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_owner_slug"
            ),
        ),
    ]
