# Generated by Django 5.2.17 on 2026-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0004_project_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="identifier_is_manual",
            field=models.BooleanField(
                default=False,
                help_text="When set, the identifier was typed by the user and is never overwritten by auto-detection.",
            ),
        ),
    ]
