# Generated by Django 5.2.17 on 2026-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0006_item_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="api_endpoint",
            field=models.CharField(
                blank=True,
                help_text="Scripted REST endpoint, e.g. GET /api/x_scope/v1/things.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="br_order",
            field=models.IntegerField(
                blank=True, help_text="Business Rule execution order.", null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="client_callable",
            field=models.BooleanField(
                default=False,
                help_text="Script Include is client callable (GlideAjax).",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="client_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="condition",
            field=models.TextField(
                blank=True, help_text="Condition / filter (Business Rule, UI Action)."
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="css_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="field_name",
            field=models.CharField(
                blank=True,
                help_text="Field an onChange Client Script watches.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="html_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="operations",
            field=models.CharField(
                blank=True,
                help_text="Operations the Business Rule runs on (e.g. insert, update).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onload", "onLoad"),
                    ("onchange", "onChange"),
                    ("onsubmit", "onSubmit"),
                    ("oncelledit", "onCellEdit"),
                    ("before", "Before"),
                    ("after", "After"),
                    ("async", "Async"),
                    ("display", "Display"),
                ],
                help_text="Client Script type (onLoad...) or Business Rule 'when' (before...).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="table_name",
            field=models.CharField(
                blank=True,
                help_text="Table the script runs on (e.g. incident).",
                max_length=80,
            ),
        ),
    ]
