# Generated by Django 5.2.17 on 2026-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0007_servicenow_component_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="api_endpoint",
            field=models.CharField(
                blank=True,
                help_text="Scripted REST endpoint, e.g. GET /api/x_scope/v1/things.",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="field_name",
            field=models.CharField(
                blank=True,
                help_text="Field an onChange Client Script watches.",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="API name other scripts use to call this one (e.g. the Script Include class name). Auto-detected from the code when left blank; used for dependency detection.",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="operations",
            field=models.CharField(
                blank=True,
                help_text="Operations the Business Rule runs on (e.g. insert, update).",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="table_name",
            field=models.CharField(
                blank=True,
                help_text="Table the script runs on (e.g. incident).",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=10000),
        ),
    ]
