# Generated by Django 5.2.17 on 2026-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0008_widen_item_field_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="scope_name",
            field=models.CharField(
                blank=True,
                help_text="Scoped app identifier, e.g. x_renin_ccr. Required when Scope is Scoped App.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scope_type",
            field=models.CharField(
                choices=[("global", "Global Scope"), ("scoped_app", "Scoped App")],
                default="global",
                help_text="Where this project's ServiceNow code lives on the instance.",
                max_length=20,
            ),
        ),
    ]
