# Generated by Django 5.2.17 on 2026-09-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0011_oauthclient_oauthauthorizationcode_oauthtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthtoken",
            name="client",
        ),
        migrations.RemoveField(
            model_name="oauthtoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="OAuthAuthorizationCode",
        ),
        migrations.DeleteModel(
            name="OAuthClient",
        ),
        migrations.DeleteModel(
            name="OAuthToken",
        ),
    ]
