# Generated by Django 5.2.17 on 2026-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0012_remove_oauthtoken_client_remove_oauthtoken_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="script_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("script_include", "Script Include"),
                    ("business_rule", "Business Rule"),
                    ("client_script", "Client Script"),
                    ("ui_page", "UI Page"),
                    ("ui_action", "UI Action"),
                    ("ui_macro", "UI Macro"),
                    ("scheduled_job", "Scheduled Job"),
                    ("fix_script", "Fix Script"),
                    ("rest_api", "Scripted REST API"),
                    ("widget", "Widget"),
                    ("xml", "XML"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
